### ISSUE TITLE
API request retry and exception

### ISSUE THREAD

**Issue by hani-j** [42Where/where42_back_v2#121]
- API request @Retryable 적용하기
- API request 로 발생하는 exception 구체화 하기

**Comment by hani-j** [comment]
- 외부 API 호출로 대부분 우리가 관리해야 하는 부분인 것 같습니다

- 주요 Exception
  - 400 BAD_REQUEST : 잘못된 요청
  - 401 UNAUTHORIZED : 토큰 권한 없음 access_token 을 확인
  - 429 TOO_MANY_REQUESTS : 1초에 2번 / 10분에 1200번 요청 횟수 초과 시
  - 500 INTERNAL_SERVER_ERROR : 외부 서버의 에러

- 고민사항
  - TooMany 의 경우 1초 후 시도하면 해소될 확률이 높아 재시도가 좋다고 생각하여 TooMany 인 경우에만 설정해 두었습니다. 1초씩 3번이면 3초인데 괜찮을까요? 
  - 더 retry 해야할 게 있을까요?
  - 400 에러시 우리가 잘못된 요청을 보냈을 경우, 401 에러시 우리 토큰 만료되었을 경우, 500 에러시 intra 다운된 경우인데 그냥 그대로 던지면 될까요? 프론트에서 오류가 발생했습니다 정보를 불러올 수 없습니다 같은 처리를 하면 되는걸까요?

**Comment by daejlee** [comment]
- 400 에러시 우리가 잘못된 요청을 보냈을 경우, 401 에러시 우리 토큰 만료되었을 경우, 500 에러시 intra 다운된 경우인데 그냥 그대로 던지면 될까요? 프론트에서 오류가 발생했습니다 정보를 불러올 수 없습니다 같은 처리를 하면 되는걸까요?

프론트 입장에서는.. 에러 코드와 같이 던져주시면 코드종류에 따라 적절히 처리하면 되서 충분할 것 같습니다. ㅎㅎ

**Comment by parksooo** [comment]
고생하셨습니다. 하은님!!
- maxAttempts = 3, backoff = @Backoff(delay = 1000)
이 부분은 default 값이면, 따로 적어두지 않아도 좋은것 같지만, 가독성 측면으로 좋은거 같아요!

- log.warn : 완전 좋은거 같아요!!! warn이라는 메서드가 있는지 처음 알았네용

- throw exception 이부분은 위의 "retry for" 어노테이션에 달린 exception으로 던지는 건가용?

**Comment by hani-j** [comment]
@daejlee 그럼 3000대로 설정된 에러가 오면 처리해주시면 감사하겠습니다!

@parksooo 
- throw exception 이부분은 위의 "retry for" 어노테이션에 달린 exception으로 던지는 건가용? 
  - 맞습니다! 그 exception 일 때만 retry 해줍니다!
