### ISSUE TITLE
Reissue

### ISSUE THREAD

**Issue by parksooo** [42Where/where42_back_v2#77]
### 처리 과정
1. Client의 api 요청
2. jwt token 만료
3. 404 에러 발생 후 Client 측 custom errorcode, message 전송
4. Client 측  "/reissue" api 요청
5. DB에서 refreshToken을 사용하여, 유효성 판단
5.1. Security context holder에 있는 intraId로 유저 정보 획득
5.2. Client 측 http header에 만료된 token을 넣어 요청 후 parse 후 유저 정보 획득
5.3. refreshToken parse 후, 만료되지 않았다면 유저정보 비교 후 accessToken 발급
5.4. refreshToken이 만료 되었다면 에러 발생
6. controller accessToken 반환

❓여기서 저희가 5.1, 5.2 방식을 정해야 합니다.
- accessToken을 받아서 parse하는 과정이 필요할까? 합니다 왜냐면 에러를 catch해야해서 조금은 자원 낭비라고 생각이 듭니다
- securityContextHolder를 사용할 때면, intraId만을 가지고만 유효성 검사하는 것이 적합한지에 대한 생각이 듭니다

의견을 남겨주시면 오늘 안으로 pr을 날리겠습니다

**Comment by hani-j** [comment]
permit all 로 열어두었는데 intraId 같은 정보만으로 유효성 검사하는게 위험하다는 생각이 들어욥 ㅠㅠ 그래서 아까도 accesstoken 으로 인증받았던 사람이라는걸 검사하자는 의견이 나왔던 것 같아요!

---

제가 열심히 서치해봤는데요!
permit all 보다 jwtfilter 에 shouldnotfilter 로 "/reissue" 적용시켜주면 어떨까요??
그러면 jwtfilter 검사 안하니까 UsernamePasswordAuthenticationFilter 에 들어갈 것 같고 인증되어있으면 잘 통과하지 않을까요?? 이렇게 되면 accesstoken 안받아도 될 것 같은데 한번 봐주세요!

**Comment by hani-j** [comment]
그럼 UsernamePasswordAuthenticationFilter 와는 상관이 없는거고.. 그냥 filter를 안거치고 api 요청이 가능하게 되버리겠네요??
그럼 accesstoken 을 검사해봐야 하지 않을까요...??

401 exception 던질 때 refresh 도 함께 주는것도 생각해봤는데 권장하지 않는 방법이라고 하네요ㅠㅠ

**Comment by parksooo** [comment]
넵 filter를 안거치고 api 요청이 가능하게 되는 겁니다!
accessToken을 검사해서 유저 정보를 get하는게 더 안전하다 생각하시는 거죠?
사실 security context holder에 넣어놓은 정보도 token parsed 해서 넣어준거라서...
팀원분들 의견도 들어보는거 좋을거같아요!

**Comment by hani-j** [comment]
security context holder 는 jwtfilter 에서 저장해주지 않나요? 
permitall 로 api 요청 들어오면 jwtfilter 를 안거치는거 아닌가요??? 그래도 security context  holder 정보는 남아있나요?

**Comment by hani-j** [comment]
제가 이해를 하지 못했어요..?
security context holder 가 token 으로 저장하는 거잖아요? 그 안에 parse 가 있고요
permit all 로 요청하게 되면 jwtfilter 를 안거치니까 token 검사도 안하고 security context holder 에 저장도 안되는거 아닌가요???

**Comment by parksooo** [comment]
음... 제가 생각했을 때는 아마 proxy 단에서 저장해놓고 사용하는거여서, 로그아웃이 될때 security Context holder를 비워주는 걸로 알고 있습니다!!!

**Comment by hani-j** [comment]
아아~ Jwtfilter 에 들어올 때마다 SecurityContextHolder 에 저장해주길래 유지가 안되는줄 알았어요!
그러면 SecurityContextHolder 에 정보가 있으니까 accesstoken 없이도 인증가능하다는 거죠??

**Comment by parksooo** [comment]
넵 그럼 일단 이렇게 해서 구현좀 해보고, 안되면 말씀 드릴께요!

**Comment by namzisun** [comment]
음 근데 securityContextHolder에 accessToken이 파싱된 게 저장되어있는 것은 맞지만, 서버 입장에서 1번, 4번이 동일한 client에게 오는 요청이라는 것을 어떻게 보장할 수 있을까요..? 동일한 client에게 오는 것이 보장되는게 아닌이상 5-2 방법인 accessToken을 다시 받는게 맞다고 생각합니다! 1번과 4번은 서버 입장에서는 별개의 request라고 생각해요~

(2번 404말고 401 혹은 custom exception으로 처리하는 게 맞을 것 같네용)

**Comment by parksooo** [comment]
동일한 클라이언트의 요청이라는 것을 보장할 수 있는 방법은 판단하기 힘들겠네요. 토큰이 없이 들어오기 때문에....
음 일단 오늘 더 알아보고 더 많은 정보를 공유하겠습니다
refreshToken에 대한 에러는 401로 던지겠습니다. + custom exception

**Comment by parksooo** [comment]
일단은 client ip와 security context holder의 intraId를 사용해서 판단하는 로직 두개 다 넣어놓았습니다
코드한번 보시고, 문제점이나 개선 방향알려주시면 논의해봐요

**Comment by parksooo** [comment]
issue 닫을 께요~
