### ISSUE TITLE
caching_groupmember

### ISSUE THREAD

**Issue by namzisun** [42Where/where42_back_v2#83]

**Comment by parksooo** [comment]
캐싱 하는 방식이 많은데
대부분 Redis을 사용한다고 합니다
redis를 사용하면 redis에 사용할 고유 entity가 필요해보여요
server local에 캐시를 저장하는 방법도 있습니다
많은 방법이 있지만, 더 효율적인 것을 찾아서 사용하면 좋을거같아요
방식을 찾게 되면 issue에 올려놓겠습니다
